name: sine_parser
dependencies:
  built_collection: any
  built_value: any
  bit_set: any
dev_dependencies:
  build: ^0.6.0
  build_runner: ^0.1.0
# built_value_generator: ^0.5.2
  built_value_generator: any
  source_gen: '>=0.5.0+03 <0.6.0'
  quiver: '>=0.21.0 <0.24.0'
  test: any
